config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs do
    resources :comments, only: [:create]
  end
  root 'blogs#index'
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs=Blog.all.page(params[:page]).order('created_at DESC').per(3)
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(blog_params)
    redirect_to root_path
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.update(blog_params)
    end
    redirect_to root_path
  end

  def destroy
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.destroy
    end
    redirect_to root_path
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new
    @comments = @blog.comments.includes(:user).order('created_at DESC')
  end

  private
  def blog_params
    params.require(:blog).permit(:title,:content,:image).merge(user_id: current_user.id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to blog_path(params[:blog_id]) }
      format.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(blog_id: params[:blog_id], user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=User.find(params[:id])
    @name=@user.name
    @blogs=@user.blogs.page(params[:page]).order('created_at DESC').per(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.haml
= render 'shared/nav'

.edit-blog
  %h3 Blog編集フォーム
  = render 'shared/form'

app/views/blogs/index.html.haml
= render 'shared/nav'
.contents
  = render 'shared/blogs'

app/views/blogs/new.html.haml
= render 'shared/nav'

.new-blog
  %h3 Blog投稿フォーム
  = render 'shared/form'

app/views/blogs/show.html.haml
= render 'shared/nav'
.blog
  .blog-title
    %h6 Title
    = @blog.title
  .blog-content
    %h6 本文
    .blog-content__image
      = image_tag @blog.image.url unless @blog.image.blank?
    .blog-content__text
      = @blog.content

.comments
  .comments-box
    %p コメント
  .comments_area
    = render partial: 'comments/list', locals: { comment: @comment}
.comment-form
  - if user_signed_in?
    = render partial: 'comments/form', locals: { comment: @comment}

app/views/comments/_form.html.haml
= form_for [@blog, @comment], id: "new_comment" do |f|
  = f.text_field :text, class: "form__comment"
  = f.submit "Send",class: "btn waves-effect waves-light",type: "submit",name: "action"

app/views/comments/_list.html.haml
- @comments.each do |comment|
  - unless comment.id.nil?
    .comment-user
      = link_to "#{comment.user.name}", user_path(comment.user.id)
    .comment-text
      =comment.text

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MiniApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / Compiled and minified CSS
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css", :rel => "stylesheet"}/
    / Compiled and minified JavaScript
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=", :src => "https://code.jquery.com/jquery-3.4.1.js"}

  %body
    = yield

app/views/shared/_blogs.html.haml
.blogs
  - @blogs.each do |blog|
    .col.s12
      .card.indigo.darken-3
        .card-content.white-text
          %span.card-title
            = blog.title
          .user-name
            Creater :
            =blog.user.name
        .card-action
          =link_to 'Show blog', blog_path(blog.id), method: :get
  = paginate(@blogs)

app/views/shared/_form.html.haml
.row
  .col.s12
    = form_for @blog do |f|
      .row
        .input-field.col.s12
          %h5 タイトル
          =f.text_field :title, class: 'textfield'
      .content
        %h5 本文
        =f.text_area :content, class: 'blog-content'
        .image
          = f.file_field :image
      = f.submit 'Send', class: 'waves-effect waves-light btn-large indigo darken-3'

app/views/shared/_nav.html.haml
%nav
  .nav-wrapper.indigo.darken-3
    =link_to 'Mini-App' ,root_path,class: 'brand-logo'
    %ul#nav-mobile.right.hide-on-med-and-down
      - if user_signed_in?
        %li
          = link_to "#{current_user.name}", user_path(current_user.id), method: :get
        %li
          = link_to 'Post Blog', new_blog_path
        %li
          = link_to 'Sign Out', destroy_user_session_path, method: :delete
      - else
        %li
          = link_to 'Sign In', new_user_registration_path
        %li
          = link_to 'New Account', new_user_session_path

app/views/users/show.html.haml
= render 'shared/nav'

.user-room
  %h5
    = current_user.name
    さんのページ
  .user-room__blogs
    - @blogs.each do |blog|
      .col.s12
        .card.indigo.darken-3
          .card-content.white-text
            %span.card-title
              = blog.title
          .card-action
            - if user_signed_in?
              =link_to 'Edit blog', edit_blog_path(blog.id)
              =link_to 'Delete blog', blog_path(blog.id), method: :delete
  = paginate(@blogs)